name: Dependency audit

on:
  schedule:
    - cron: "0 0 * * 1" # midnight on Monday
  workflow_dispatch:

jobs:
  security-audit:
    name: Dependency audit
    runs-on: ubuntu-latest
    permissions:
      issues: write
      checks: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Audit dependencies
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
